---
- name: Install Ceph storage plugin dependencies
  package:
    name: ceph-common
    state: present
    update_only: true
  when: not openshift_is_atomic | bool
  register: result
  until: result is succeeded
